replicaCount: 1

image:
  repository: nileshzarkar/htmlpage
  pullPolicy: Always
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  appName: htmlDynamicPage
podLabels:
  environment: dev

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8082
  nodePort: 30082
  targetPort: 8082

config:
  pageColor: "red"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /q/health/live
    port: 8082
  initialDelaySeconds: 5
  periodSeconds: 5  
readinessProbe:
  httpGet:
    path: /q/health/ready
    port: 8082
  initialDelaySeconds: 5
  periodSeconds: 5  

autoscaling:
  enabled: false
  # enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

volumeMounts:
  - name: config-volume
    mountPath: /app/config
  - name: data-volume
    mountPath: /app/data

nodeSelector: {}

tolerations: []

affinity: {}

namespaces:
  - name: namespace1
  - name: namespace2
  - name: namespace3

environments:
  - name: dev
  - name: qa
  - name: uat  
  - name: prod

env:
  - name: APP_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"
  - name: FEATURE_FLAG
    value: "true"  