serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'currency-service'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['currency-service:8080']

      - job_name: 'exchange-service'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['exchange-service:8081']