apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - name: currency-container
          image: niles/currency:1.0.0  # Replace with your actual image name
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  selector:
    app: currency
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Expose port 30080 on the node (localhost)
  type: NodePort
