apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlpage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmlpage
  template:
    metadata:
      labels:
        app: htmlpage
    spec:
      containers:
        - name: htmlpage-container
          image: niles/htmlpage:1.0.0  # Replace with your actual image name
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: htmlpage-service
spec:
  selector:
    app: htmlpage
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082  # Expose port 30081 on the node (localhost)
  type: NodePort
